root: ./

redirects:
  develop/get-started-guide: developers/learn/overview-of-xion.md
  developers/learn/overview-of-xion: xions-core/learn/README.md
  developers/getting-started-advanced/your-first-dapp/xion-typescript: developers/getting-started-advanced/your-first-dapp/backend-adaption/xion-backend-using-cosmjs.md
